// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RomaF5patioComidas.Models
{
    public partial class Bebida
    {
        public Bebida()
        {
            Pedido = new HashSet<Pedido>();
        }

        public int IdBebida { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public double? Precio { get; set; }
        public int? Stock { get; set; }
        public int IdTipobebida { get; set; }
        public bool? Eliminar { get; set; }

        public virtual TipoBebida IdTipobebidaNavigation { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}