// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RomaF5patioComidas.Models
{
    public partial class CategoriaUser
    {
        public CategoriaUser()
        {
            Usuario = new HashSet<Usuario>();
        }

        public int IdCategoria { get; set; }
        public string Categoria { get; set; }

        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}