// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RomaF5patioComidas.Models
{
    public partial class Menu
    {
        public Menu()
        {
            Pedido = new HashSet<Pedido>();
        }

        public int IdMenu { get; set; }
        public string Nombre { get; set; }
        public int? Precio { get; set; }
        public string Descripcion { get; set; }
        public bool? Eliminar { get; set; }

        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}