// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RomaF5patioComidas.Models
{
    public partial class TipoBebida
    {
        public TipoBebida()
        {
            Bebida = new HashSet<Bebida>();
        }

        public int IdTipobebida { get; set; }
        public double? Litros { get; set; }
        public bool? Eliminar { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<Bebida> Bebida { get; set; }
    }
}